import Analysis from '../pages/dashboard/analysis/analysis';
import Monitor from '../pages/dashboard/monitor';
import Workplace from '../pages/dashboard/workplace';

export default [
  {
    id: 1,
    rank: 1,
    name: 'Dashboard',
    icon: 'dashboard',
  },
  {
    id: 11,
    pid: 1,
    rank: 2,
    name: '分析页',
    path: '/dashboard/analysis',
    component: Analysis,
  },
  {
    id: 12,
    pid: 1,
    rank: 2,
    name: '监控页',
    path: '/dashboard/monitor',
    component: Monitor,
  },
  {
    id: 13,
    pid: 1,
    rank: 2,
    name: '工作台',
    path: '/dashboard/workplace',
    component: Workplace,
  },
  {
    id: 2,
    rank: 1,
    name: '表单页',
    icon: 'dashboard',
  },
  {
    id: 21,
    pid: 2,
    rank: 2,
    name: '基础表单',
    path: '/dashboard/analysis',
    component: Analysis,
  },
  {
    id: 22,
    pid: 2,
    rank: 2,
    name: '分步表单',
    path: '/dashboard/monitor',
    component: Monitor,
  },
  {
    id: 23,
    pid: 2,
    rank: 2,
    name: '高级表单',
    path: '/dashboard/workplace',
    component: Workplace,
  },
  {
    id: 3,
    rank: 1,
    name: '列表页',
    icon: 'dashboard',
  },
  {
    id: 31,
    pid: 3,
    rank: 2,
    name: '查询表格',
    path: '/dashboard/analysis',
    component: Analysis,
  },
  {
    id: 32,
    pid: 3,
    rank: 2,
    name: '标准列表',
    path: '/dashboard/monitor',
    component: Monitor,
  },
  {
    id: 33,
    pid: 3,
    rank: 2,
    name: '卡片列表',
    path: '/dashboard/workplace',
    component: Workplace,
  },
  {
    id: 34,
    pid: 3,
    rank: 2,
    name: '搜索列表',
    path: '/dashboard/workplace',
    component: Workplace,
  },
  {
    id: 4,
    rank: 1,
    name: '详情页',
    icon: 'dashboard',
  },
  {
    id: 41,
    pid: 4,
    rank: 2,
    name: '基础详情页',
    path: '/dashboard/analysis',
    component: Analysis,
  },
  {
    id: 42,
    pid: 4,
    rank: 2,
    name: '高级详情页',
    path: '/dashboard/monitor',
    component: Monitor,
  },
  {
    id: 5,
    rank: 1,
    name: '结果页',
    icon: 'dashboard',
  },
  {
    id: 51,
    pid: 5,
    rank: 2,
    name: '成功页',
    path: '/dashboard/analysis',
    component: Analysis,
  },
  {
    id: 52,
    pid: 5,
    rank: 2,
    name: '失败页',
    path: '/dashboard/monitor',
    component: Monitor,
  },
  {
    id: 6,
    rank: 1,
    name: '个人页',
    icon: 'dashboard',
  },
  {
    id: 61,
    pid: 6,
    rank: 2,
    name: '个人中心',
    path: '/dashboard/analysis',
    component: Analysis,
  },
  {
    id: 62,
    pid: 6,
    rank: 2,
    name: '个人设置',
    path: '/dashboard/monitor',
    component: Monitor,
  },
];
